version: '3'

services:
    postgres:
        image: postgres:14
        environment:
            POSTGRES_PASSWORD: ecommerce
            POSTGRES_USER: ecommerce
            POSTGRES_DB: ecommerce
        ports:
            - 5433:5433
